dist: xenial
sudo: required
arch:
  - amd64

language: python
cache: pip

notifications:
  email: false

env:
  - H5PY_VERSION="==2.6" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.8" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.10" EXTRA_PACKAGES="libquadmath0"

python:
  - "3.5"
  - "3.7"
  - "3.9"

jobs:
  include:
    - python: "3.9"
      env: H5PY_VERSION="==2.10" EXTRA_PACKAGES=""
      arch: ppc64le
    - python: "3.9"
      env: H5PY_VERSION="==2.10" EXTRA_PACKAGES=""
      arch: s390x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc libhdf5-serial-dev libblas-dev liblapack-dev libatlas-dev libatlas-base-dev $EXTRA_PACKAGES
  - sudo chown -R $USER:$GROUP ~/.cache/pip/wheels # Fix for non-amd64 architectures

# command to install dependencies
#
# Seem to need newer Numpy and Cython as well.
install:
  - pip install -U numpy Cython
  - pip install h5py$H5PY_VERSION
  - pip install -r requirements_tests.txt
  - pip install -e examples/example_hdf5storage_marshaller_plugin

# command to run tests
script: pytest
