name: Build wheel

on:
  push:
    branches:
      - numpy2
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - 'requirements**.txt'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build-wheel:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install build dependencies
        run: |
          python -m pip install build
      - name: Build wheel and sdist
        run: |
          python -m build .
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: Wheel and sdist
          path: dist
