name: Lint source code

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - 'requirements**.txt'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install -U ruff==0.0.227
      - name: Lint with ruff
        run: |
          python -m ruff --format=github .
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install -U pylint==2.15.10
          python -m pip install .
      - name: Lint with pylint
        run: |
          python -m pylint src/*/*.py
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install -U mypy==0.991 types-setuptools
          python -m pip install .
      - name: Type checking with mypy
        run: |
          python -m mypy src/
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install -U black==22.12.0
      - name: Formatting with black
        run: |
          python -m black --diff --check src/*/*.py tests/*.py examples/*/src/*/*.py
