name: linting-ruff

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - 'requirements**.txt'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install -U ruff
      - name: Lint with ruff
        run: ruff --format=github .
