name: Unit tests and lint checks

on:
  push:
    branches:
      - typing_ci_test
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - '.gitignore'
      - '.gitattributes'

jobs:
  tests:
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        h5py-version:
          - '>=3.12,<3.13'
          - '' # latest
        numpy-version:
          - '>=2.1,<2.2'
          - '' # latest
        include:
          - os: 'ubuntu-24.04' # There are no NumPy 1.26 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: ''
            numpy-version: '>=1.26,<2.0'
          - os: 'windows-2022' # There are no NumPy 1.26 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: ''
            numpy-version: '>=1.26,<2.0'
          - os: 'ubuntu-24.04' # there are no h5py 3.11 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.11,<3.12'
            numpy-version: ''
          - os: 'windows-2022' # there are no h5py 3.11 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.11,<3.12'
            numpy-version: ''
          - os: 'ubuntu-24.04' # there are no h5py 3.10 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.10,<3.11'
            numpy-version: '<2.0'
          - os: 'windows-2022' # there are no h5py 3.10 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.10,<3.11'
            numpy-version: '<2.0'
          - os: 'ubuntu-24.04' # there are no h5py 3.9 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.9,<3.10'
            numpy-version: '<2.0'
          - os: 'windows-2022' # there are no h5py 3.9 binaries for Python 3.13
            python-version: '3.11'
            h5py-version: '>=3.9,<3.10'
            numpy-version: '<2.0'
          - os: 'ubuntu-24.04'
            python-version: '3.10'
            h5py-version: '>=3.9,<3.10'
            numpy-version: '<2.0'
          - os: 'windows-2022'
            python-version: '3.10'
            h5py-version: '>=3.9,<3.10'
            numpy-version: '<2.0'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies including h5py ${{ matrix.h5py-version }} and NumPy ${{matrix.numpy-version}}
      env:
        H5PY_VERSION: ${{ matrix.h5py-version }}
        NUMPY_VERSION: ${{ matrix.numpy-version}}
      shell: bash
      run: |
        python -m pip install numpy$NUMPY_VERSION h5py$H5PY_VERSION
        python -m pip install .[scipy,tests]
    - name: Test with pytest
      run: |
        pytest tests

  tests-no-scipy:
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
        python-version:
          - '3.13'
        h5py-version:
          - '' # latest
        numpy-version:
          - '' # latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies including h5py ${{ matrix.h5py-version }} and NumPy ${{matrix.numpy-version}}
      env:
        H5PY_VERSION: ${{ matrix.h5py-version }}
        NUMPY_VERSION: ${{ matrix.numpy-version}}
      shell: bash
      run: |
        python -m pip install numpy$NUMPY_VERSION h5py$H5PY_VERSION
        python -m pip install .[tests]
    - name: Test with pytest
      run: |
        pytest tests

  build-docs:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python -m pip install .[docs]
      - name: Build html docs
        working-directory: ./doc
        run: |
          make html
      - name: Upload html docs
        uses: actions/upload-artifact@v4
        with:
          name: HTML docs
          path: doc/build/html

  lint:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python -m pip install .[docs,scipy,tests]
      - name: Lint the code
        run: |
          ruff check . --config=pyproject.toml
      - name: Check dependencies
        run: |
          deptry . --config pyproject.toml

  typechecking:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-24.04'
            python-version: '3.10'
            numpy-version: '<2.0'
          - os: 'ubuntu-24.04'
            python-version: '3.12'
            numpy-version: '<2.0'
          - os: 'ubuntu-24.04'
            python-version: '3.10'
            numpy-version: ''  # latest
          - os: 'ubuntu-24.04'
            python-version: '3.13'
            numpy-version: ''  # latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Python dependencies including NumPy ${{matrix.numpy-version}}
      env:
        NUMPY_VERSION: ${{ matrix.numpy-version}}
      shell: bash
      run: |
        python -m pip install numpy$NUMPY_VERSION
        python -m pip install .[typechecking,scipy,tests]
    - name: Check typing of hdf5storage, tests, and examples with mypy
      run: |
        mypy tests
        mypy examples
