name: unit-tests

on:
  push:
    branches:
      - numpy2
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.13'
        h5py-version:
          - '>=3.12,<3.13'
          - '>=3.13,<3.14'
        numpy-version:
          - '>=1.26,<2.0'
          - '>=2.0,<2.1'
          - '>=2.1,<2.2'
          - '>=2.2,<2.3'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies including h5py ${{ matrix.h5py-version }} and NumPy ${{matrix.numpy-version}}
      env:
        H5PY_VERSION: ${{ matrix.h5py-version }}
        NUMPY_VERSION: ${{ matrix.numpy-version}}
      run: |
        python -m pip install numpy$NUMPY_VERSION h5py$H5PY_VERSION pytest
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests
